sudo: false
dist: trusty
language: node_js
node_js:
  - 6
script: npm run-script ci
before_install:
  npm install -g yarn;
  yarn install --ignore-optional
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.electron
addons:
  apt:
    packages:
      - rpm
      - lintian
after_success:
  - lintian test/fixtures/hadron-app/dist/*.deb
